module:
  registry: alibaba-nacos-discovery-server

beta:
  namespace: 1225f02b-e9bd-493f-8140-fb4232562a00
spring:
  application:
    name: userCenter
  cloud:
    nacos:
      discovery:
        server-addr:  119.91.75.103:8846
    sentinel:
      transport:
        dashboard:  119.91.75.103:8858
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            namespace: ${beta.namespace}
            dataId: ${spring.application.name}-flow-rules
            groupId: DEV_GROUP
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            namespace: ${beta.namespace}
            dataId: ${spring.application.name}-degrade-rules
            groupId: DEV_GROUP
            data-type: json
            rule-type: degrade
  data:
    #mongodb
    mongodb:
      host: 120.79.187.144
      port: 27017
      database: user
      username: root
      password: 123456
  #redis 配置
  redis:
#    host: 120.79.187.144
#    port: 6379
#    password: 123456
    sentinel:
      master: mymaster
      nodes: 120.79.187.144:26379,120.79.187.144:26380,120.79.187.144:26381 # 哨兵的ip:port列表
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    timeout: 6000

swagger:
  base-package: com.zjsn.user.controller
  version: 1.0
  title: 用户中心模块文档
  description: 用户中心相关的api文档
  contact:
    name: zjsn
    email: zjsn233@gmail.com