module:
  registry: alibaba-nacos-discovery-server

spring:
  cloud:
    nacos:
      discovery:
        server-addr:  120.79.187.144:8846
  data:
    #mongodb
    mongodb:
      host: 120.79.187.144
      port: 27017
      database: user
      username: root
      password: 123456