module:
  registry: alibaba-nacos-discovery-server
  userCenter: userCenter

beta:
  namespace: 1225f02b-e9bd-493f-8140-fb4232562a00
spring:
  application:
    name: authorityCenter
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.187.144:8846
    sentinel:
      transport:
        dashboard: 119.91.75.103:8858
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            namespace: ${beta.namespace}
            dataId: ${spring.application.name}-flow-rules
            groupId: DEV_GROUP
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            namespace: ${beta.namespace}
            dataId: ${spring.application.name}-degrade-rules
            groupId: DEV_GROUP
            data-type: json
            rule-type: degrade

  data:
    #mongodb
    mongodb:
      host: 120.79.187.144
      port: 27017
      database: user
      username: root
      password: 123456
#feign 是否使用哨兵
feign:
  sentinel:
    enabled: true
swagger:
  base-package: com.zjsn.authority.controller
  version: 1.0
  title: 权限中心模块文档
  description: 权限中心相关的api文档
  contact:
    name: zjsn
    email: zjsn233@gmail.com