module:
  registry: alibaba-nacos-discovery-server
  userCenter: userCenter

spring:
  application:
    name: authorityCenter
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.187.144:8846
    sentinel:
      transport:
        dashboard: localhost:8858
      datasource:
        ds:
          nacos:
            server-addr: 120.79.187.144:8846
            namespace: 1225f02b-e9bd-493f-8140-fb4232562a00
            dataId: ${spring.application.name}-sentinel
            groupId: DEV_GROUP
            rule-type: flow
  data:
    #mongodb
    mongodb:
      host: 120.79.187.144
      port: 27017
      database: user
      username: root
      password: 123456